#!/usr/bin/env bash
# Wrap the Tauri v1 desktop build into a SINGLE-FILE, SELF-CONTAINED AppImage that runs on
# glibc 2.31 (Kylin V10, Debian 11, Ubuntu 20.04) — with no system GUI libraries installed.
#
# Consumes what build_desktop_v1.sh already staged (dist-portable-v1/<name>/), so run that
# first. It is the single source of truth for the payload: the same shell binary, the same
# PyInstaller sidecar, already asserted to be ≤ the glibc ceiling.
#
# Why an AppImage is possible HERE but not for the v2 shell:
#
#   The AppImage container is a type-2 runtime. Whether it is statically or dynamically linked is
#   irrelevant to the portability claim as long as its OWN glibc demand is ≤ the target's — and
#   AppImageKit's runtime only needs very old symbols, so it runs on glibc 2.31. The thing that
#   sank the v2 AppImage was its CONTENTS: libgtk-3.so.0 / libwebkit2gtk-4.1.so.0 built against
#   glibc 2.38.
#
#   And those contents came from the HOST, not from a download. linuxdeploy-plugin-gtk resolves
#   every path through the host's own pkg-config and copies the host's packages, so building in
#   a bullseye container bundles bullseye's GTK3/WebKitGTK 4.0 — which is exactly the ABI the
#   RHEL-8 family has. (An earlier comment in build_desktop_v1.sh claimed the plugin downloads a
#   prebuilt glibc-2.38 GTK; that is wrong, and is corrected there.)
#
# Differences from Tauri's own AppImage bundler (which cannot be used: v2's CLI cannot build a
# v1 app, and v1's bundler builds the AppDir from a *deb* step whose `resources` we deliberately
# do not configure):
#   * we assemble the AppDir ourselves instead of `cp -r ../appimage_deb/data/usr`
#   * we run linuxdeploy + appimagetool explicitly rather than through the Tauri CLI
#   * we WRITE OUR OWN AppRun, because the plugin's autogenerated one does not cover WebKit
#
# Prerequisites in the build container: the v1 GUI -dev packages (the plugin needs the .pc
# files), dpkg-dev, patchelf, binutils, plus aarch64 linuxdeploy/appimagetool.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PLATFORM="$(cd "$HERE/.." && pwd)"
GUI="$PLATFORM/surfaces/gui"

VERSION="$(node -p "require('$GUI/src-tauri/tauri.conf.json').version")"
TRIPLE="$(rustc -vV | sed -n 's/host: //p')"
ARCH="${TRIPLE%%-*}"
GLIBC_MAX="${OCW_GLIBC_MAX:-2.31}"

# The staging dir build_desktop_v1.sh leaves behind.
SRC="$HERE/dist-portable-v1/openworker-$VERSION-linux-$ARCH-desktop"

WORK="$HERE/build-appimage-v1"
TOOLS="$WORK/tools"
APPDIR="$WORK/OpenWorker.AppDir"
DIST="$HERE/dist-appimage-v1"

# Multiarch triplet dir the WebKit helpers live in. dpkg knows it; fall back to the convention.
MULTIARCH="$(dpkg-architecture -qDEB_HOST_MULTIARCH 2>/dev/null || echo "$ARCH-linux-gnu")"
WEBKIT_TRIPLET="/usr/lib/$MULTIARCH/webkit2gtk-4.0"

# Tauri fetches the plugin from its own fork; that is the copy their pipelines are proven
# against, so use the same one rather than upstream master.
PLUGIN_URL="https://raw.githubusercontent.com/tauri-apps/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh"

echo "==> arch $ARCH  multiarch $MULTIARCH  version $VERSION  glibc ceiling $GLIBC_MAX"
echo "==> webkit2gtk-4.0 dev: $(pkg-config --modversion webkit2gtk-4.0 2>/dev/null || echo '<MISSING — the plugin needs its .pc file>')"
echo "==> gtk+-3.0 dev:       $(pkg-config --modversion gtk+-3.0 2>/dev/null || echo '<MISSING>')"
[ -d "$SRC" ] || { echo "ERROR: no staged tree at $SRC — run packaging/build_desktop_v1.sh first" >&2; exit 1; }

echo "==> [1/7] fetching the AppImage toolchain (linuxdeploy, plugin, appimagetool)"
mkdir -p "$TOOLS"
fetch() { # fetch <url> <dest>
  if [ ! -s "$2" ]; then
    echo "    $(basename "$2")"
    curl -fsSL --retry 5 --retry-delay 3 --retry-all-errors "$1" -o "$2"
  fi
}
fetch "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-$ARCH.AppImage" \
      "$TOOLS/linuxdeploy.AppImage"
fetch "$PLUGIN_URL" "$TOOLS/linuxdeploy-plugin-gtk"
fetch "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$ARCH.AppImage" \
      "$TOOLS/appimagetool.AppImage"
chmod +x "$TOOLS/linuxdeploy.AppImage" "$TOOLS/linuxdeploy-plugin-gtk" "$TOOLS/appimagetool.AppImage"
# Record what we actually built with: these are rolling `continuous` downloads.
sha256sum "$TOOLS/linuxdeploy.AppImage" "$TOOLS/linuxdeploy-plugin-gtk" "$TOOLS/appimagetool.AppImage"

# linuxdeploy finds its plugins by name in PATH.
export PATH="$TOOLS:$PATH"
export LINUXDEPLOY="$TOOLS/linuxdeploy.AppImage"
# Pin the library root so the plugin's path rewrites are predictable.
export LD_GTK_LIBRARY_PATH="/usr/lib/$MULTIARCH"
export DEPLOY_GTK_VERSION=3
# There is no FUSE in a build container, and `--appimage-extract-and-run` only covers the one
# invocation it is passed to. The plugin re-invokes linuxdeploy ITSELF (with the same
# LINUXDEPLOY path) partway through, so the flag alone is not enough — this env var makes every
# AppImage in this environment extract and run instead of trying to loopback-mount.
export APPIMAGE_EXTRACT_AND_RUN=1

echo "==> [2/7] assembling the AppDir from the staged tree"
rm -rf "$APPDIR"
# usr/lib/OpenWorker has to exist before the sidecar copy: `cp -R src a/b/c` creates only the
# last component, so a missing parent fails with "No such file or directory" on the destination.
mkdir -p "$APPDIR/usr/bin" \
         "$APPDIR/usr/lib/OpenWorker" \
         "$APPDIR/usr/share/applications" \
         "$APPDIR/usr/share/icons/hicolor/128x128/apps" \
         "$APPDIR/usr/share/doc/openworker"

cp "$SRC/openworker-desktop" "$APPDIR/usr/bin/openworker-desktop"
chmod +x "$APPDIR/usr/bin/openworker-desktop"

# The sidecar goes under usr/lib/<Product>/sidecar — NOT usr/bin — for two reasons:
#   1. the shell's server_bin() probes <exe dir>/sidecar first and then scans usr/lib/*/sidecar,
#      so this is a layout it already looks in (it is the one the deb uses);
#   2. usr/bin is what linuxdeploy runs `ldd`+patchelf over, and running patchelf across a
#      ~2500-file PyInstaller onedir is both pointless and a good way to break it.
cp -RL "$SRC/sidecar" "$APPDIR/usr/lib/OpenWorker/sidecar"
chmod +x "$APPDIR/usr/lib/OpenWorker/sidecar/openworker-server"

cp "$SRC/openworker-desktop.png" "$APPDIR/usr/share/icons/hicolor/128x128/apps/openworker.png"
cp "$SRC/openworker-desktop.png" "$APPDIR/openworker.png"
cp "$SRC/openworker-desktop.png" "$APPDIR/.DirIcon"
cp "$SRC/README.txt" "$APPDIR/usr/share/doc/openworker/README.txt" 2>/dev/null || true

cat > "$APPDIR/usr/share/applications/openworker.desktop" <<'DESKTOP'
[Desktop Entry]
Type=Application
Name=OpenWorker
Comment=Local-first AI coworker
Exec=openworker-desktop
Icon=openworker
Terminal=false
Categories=Utility;Development;
StartupWMClass=openworker-desktop
DESKTOP

echo "==> [3/7] copying the WebKitGTK helper processes (ldd cannot see them)"
# WebKitWebProcess / WebKitNetworkProcess / the injected bundle are EXECUTED BY PATH, not
# linked, so linuxdeploy's ldd pass will never bring them in. Without them the webview cannot
# render at all, and the failure on a machine that has no system WebKitGTK is a blank window
# plus a "Failed to start the WebKitWebProcess" in the log. Tauri's own bundler handles this
# with three `find -name ... -exec cp --parents` calls; copying the whole directory is the same
# thing without the guesswork about which files matter.
if [ -d "$WEBKIT_TRIPLET" ]; then
  echo "    from $WEBKIT_TRIPLET"
  mkdir -p "$APPDIR/usr/lib/$MULTIARCH"
  cp -RL "$WEBKIT_TRIPLET" "$APPDIR/usr/lib/$MULTIARCH/"
  find "$APPDIR/usr/lib/$MULTIARCH/webkit2gtk-4.0" -maxdepth 1 -type f -printf '      %f\n' | sort
else
  echo "ERROR: $WEBKIT_TRIPLET does not exist — the -dev package is not installed" >&2
  exit 1
fi

echo "==> [4/7] linuxdeploy + linuxdeploy-plugin-gtk (this pulls the GTK/WebKit closure)"
# --appimage-extract-and-run: there is no FUSE in a container, and we do not want to depend on
# the host having it either. No --output here: appimagetool runs in [6/7] so that our own AppRun
# survives (linuxdeploy would overwrite it).
"$LINUXDEPLOY" --appimage-extract-and-run --appdir "$APPDIR" --plugin gtk

echo "==> [4.5/7] completeness pass: bundle any NEEDED library linuxdeploy skipped"
# linuxdeploy applies an excludelist (libX11, libfontconfig, libGL, libxcb, libwayland-client,
# libdrm, …) and the smoke host installs exactly that core set, so those are left to the host.
# But occasionally a genuinely-bundled dependency is missed (we hit libharfbuzz.so.0). Scan every
# ELF in the AppDir, and for each NEEDED library that is absent from the bundle, copy it from the
# build environment (bullseye — the correct glibc-2.31 ABI), skipping only the host-provided
# excludelist so we never ship a conflicting copy of a system library.
HOST_LIB="/usr/lib/$MULTIARCH"
SKIP=" libX11.so.6 libfontconfig.so.1 libfreetype.so.6 libexpat.so.1 libGL.so.1 libEGL.so.1 libGLX.so.0 libGLdispatch.so.0 libOpenGL.so.0 libxcb.so.1 libwayland-client.so.0 libdrm.so.2 libgbm.so.1 libxkbcommon.so.0 libc.so.6 libm.so.6 libpthread.so.0 libdl.so.2 librt.so.1 libresolv.so.2 ld-linux-aarch64.so.1 "
bundled=0
for elf in $(find "$APPDIR" -type f 2>/dev/null); do
  [ -f "$elf" ] || continue
  for lib in $(readelf -d "$elf" 2>/dev/null | sed -n 's/.*NEEDED.*\[\([^]]*\)\].*/\1/p'); do
    case "$SKIP" in
      *" $lib "*) continue ;;
    esac
    if find "$APPDIR/usr/lib" -name "$lib" 2>/dev/null | grep -q .; then
      continue
    fi
    src="$HOST_LIB/$lib"
    if [ -e "$src" ]; then
      cp -L "$src" "$APPDIR/usr/lib/$MULTIARCH/" 2>/dev/null \
        && echo "    bundled missing $lib (needed by $(basename "$elf"))" \
        && bundled=$((bundled + 1))
    else
      echo "    WARN: $lib needed by $(basename "$elf") is neither in the AppDir nor the host env"
    fi
  done
done
echo "    completeness pass: $bundled library(ies) bundled from the environment"

echo "==> [5/7] writing our own AppRun"
# Two things the autogenerated AppRun does not do, and both are load-bearing for the claim
# "runs on a machine with no system WebKitGTK":
#   * LD_LIBRARY_PATH into the bundle — the WebKit helper processes are raw binaries we copied
#     by hand, so nothing has given them an rpath, and they are children of this process;
#   * WEBKIT_EXEC_PATH — without it WebKitGTK looks for its helpers at the compile-time
#     PKGLIBEXECDIR, i.e. /usr/lib/<multiarch>/webkit2gtk-4.0 on the TARGET machine, which by
#     definition does not have it.
# The plugin's apprun-hooks are still sourced: they set GTK_PATH, GTK_IM_MODULE_FILE,
# GDK_PIXBUF_MODULE_FILE and GSETTINGS_SCHEMA_DIR, all of which point into the bundle and all
# of which the gate above the caches in loaders.cache / immodules.cache was rewritten for.
#
# rm first, and this is not cosmetic: linuxdeploy may leave AppRun as a SYMLINK to
# usr/bin/openworker-desktop, in which case `cat > AppRun` would follow the link and overwrite
# the application binary with a shell script.
rm -f "$APPDIR/AppRun"
cat > "$APPDIR/AppRun" <<APPRUN
#!/bin/sh
# AppRun for the OpenWorker AppImage. POSIX sh on purpose: the target's /bin/sh may be dash.
set -eu
HERE="\$(cd "\$(dirname "\$0")" && pwd)"
APPDIR="\${APPDIR:-\$HERE}"
# Canonicalise to an absolute path FIRST. The AppImage runtime may hand us a RELATIVE
# APPDIR, and every path derived from it inherits that - which is exactly what happened:
# WebKit resolved its helpers against "." and tried
#   "././/lib/aarch64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess"
# (note the missing usr/ component) instead of the bundled copy.
APPDIR="\$(cd "\$APPDIR" && pwd)"
export APPDIR
# linuxdeploy places the whole GTK/WebKit closure in the multiarch subdir
# (usr/lib/<triplet>), NOT in usr/lib. The dynamic loader does not search that subdir
# recursively, and the rpath linuxdeploy rewrites only points at usr/lib — so without the
# multiarch dir here, every bundled library (libharfbuzz, libwebkit2gtk, …) is "not found"
# and the binary dies on launch. This is the single thing that makes the bundle self-contained.
export LD_LIBRARY_PATH="\$APPDIR/usr/lib:\$APPDIR/usr/lib/$MULTIARCH\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
# The WebKit helpers live beside the bundled libwebkit2gtk, in the multiarch subdirectory our
# build copied them to. Point WebKit at them instead of at the target machine's /usr/lib.
if [ -d "\$APPDIR/usr/lib/$MULTIARCH/webkit2gtk-4.0" ]; then
  export WEBKIT_EXEC_PATH="\$APPDIR/usr/lib/$MULTIARCH/webkit2gtk-4.0"
fi
# WebKitGTK under some ARM64 Mesa drivers renders a black window without these.
export WEBKIT_DISABLE_COMPOSITING_MODE="\${WEBKIT_DISABLE_COMPOSITING_MODE:-1}"
export WEBKIT_DISABLE_DMABUF_RENDERER="\${WEBKIT_DISABLE_DMABUF_RENDERER:-1}"
export XDG_DATA_DIRS="\$APPDIR/usr/share:\${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
if [ -d "\$APPDIR/apprun-hooks" ]; then
  for hook in "\$APPDIR"/apprun-hooks/*; do
    [ -f "\$hook" ] || continue
    # shellcheck disable=SC1090
    . "\$hook"
  done
fi
# Set the helper path AFTER sourcing the hooks, deliberately: linuxdeploy-plugin-gtk's
# hook exports its own WebKit/GTK variables, so anything exported before this point can
# be silently overridden (and was - see above). The helpers live beside the bundled
# libwebkit2gtk, in the multiarch subdirectory our build copied them to; point WebKit at
# them instead of at the target machine's /usr/lib, which does not have them.
if [ -d "\$APPDIR/usr/lib/$MULTIARCH/webkit2gtk-4.0" ]; then
  export WEBKIT_EXEC_PATH="\$APPDIR/usr/lib/$MULTIARCH/webkit2gtk-4.0"
fi
# Diagnostics are OPT-IN, and that is load-bearing rather than tidiness. They go to stderr,
# so they land in the smoke job's app.log - and that job greps app.log for the string
# "WEBKIT_EXEC_PATH" to detect WebKit failing to find its helper. Printing it unconditionally
# made the job fail on its own debug output while the app was in fact rendering fine (window
# mapped, webview hitting the API). Export APPRUN_DEBUG=1 to get them back.
if [ -n "\${APPRUN_DEBUG:-}" ]; then
  echo "APPRUN: APPDIR=\$APPDIR" >&2
  echo "APPRUN: WEBKIT_EXEC_PATH=\${WEBKIT_EXEC_PATH:-<unset>}" >&2
  ls -la "\$APPDIR/usr/lib/$MULTIARCH/webkit2gtk-4.0" >&2 \
    || echo "APPRUN: helper dir MISSING" >&2
  echo "APPRUN: PWD=\$(pwd)" >&2
  echo "APPRUN: target=\$APPDIR/usr/bin/openworker-desktop" >&2
  env | grep -E '^(GTK_|GDK_|GSETTINGS|WEBKIT)' | sed 's/^/APPRUN ENV: /' >&2 || true
fi
# Run from the AppDir root. This WebKitGTK release derives its helper path from the
# executable's location rather than honouring WEBKIT_EXEC_PATH, producing a RELATIVE
# path with no usr/ component; making the AppDir root the working directory gives that
# derivation its best chance of landing on the bundled helpers.
cd "\$APPDIR"
exec "\$APPDIR/usr/bin/openworker-desktop" "\$@"
APPRUN
chmod +x "$APPDIR/AppRun"
rm -f "$APPDIR/AppRun.wrapped"   # linuxdeploy's launcher; we exec the binary ourselves
ln -sf "usr/share/applications/openworker.desktop" "$APPDIR/openworker.desktop"
# Belt and braces for the relative helper path above: whatever base WebKit derives,
# "<base>/lib/<triplet>/webkit2gtk-4.0" has to resolve, and the helpers actually live
# under usr/lib/<triplet>/webkit2gtk-4.0. Exposing usr/lib as ./lib covers the shape
# that has no usr/ component. Relative target on purpose - it must keep working after
# the AppImage is unpacked somewhere else entirely.
ln -sfn "usr/lib" "$APPDIR/lib"

echo "==> [6/7] glibc ceiling on the AppDir, then appimagetool"
"${OCW_PYTHON:-python3}" "$HERE/check_glibc_ceiling.py" --max "$GLIBC_MAX" "$APPDIR"

mkdir -p "$DIST"
OUT="$DIST/openworker-$VERSION-linux-$ARCH-desktop.AppImage"
rm -f "$OUT" "$DIST/SHA256SUMS"
# ARCH is what appimagetool needs to name and to pick its runtime; it cannot infer it here.
ARCH="$ARCH" "$TOOLS/appimagetool.AppImage" --appimage-extract-and-run \
  "$APPDIR" "$OUT"
chmod +x "$OUT"

echo "==> [7/7] verifying the finished file"
echo "    size: $(du -h "$OUT" | cut -f1)"
# We do NOT assert the runtime is statically linked. AppImageKit's `appimagetool` ships a
# *dynamically* linked runtime (it has a PT_INTERP); that is fine as long as the runtime's own
# GLIBC_* demand is ≤ the ceiling — AppImageKit's runtime only needs very old symbols, so it runs
# on glibc 2.31. The check below scans the runtime ELF's version-needs table (the same data the
# loader consults) and fails only if the runtime genuinely demands a newer glibc than the target.
"${OCW_PYTHON:-python3}" "$HERE/check_glibc_ceiling.py" --appimage --max "$GLIBC_MAX" "$OUT"

( cd "$DIST" && sha256sum "openworker-$VERSION-linux-$ARCH-desktop.AppImage" > SHA256SUMS )

echo ""
echo "Done. Artifacts under: $DIST"
ls -la "$DIST"
cat "$DIST/SHA256SUMS"
